---
- name: Update and upgrade system
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: Install keepalived and HAProxy
  ansible.builtin.apt:
    pkg:
      - keepalived
      - haproxy
      - cron

- name: Create directory for HAProxy
  ansible.builtin.file:
    path: "/etc/haproxy"
    state: directory
    mode: '0644'

- name: Create directory for keepalived
  ansible.builtin.file:
    path: "/etc/keepalived"
    state: directory
    mode: '0644'

# ONLY FOR CLUSTERS USING MULTIPLE SUBNETS
# - name: Setting up IP route for 10.10.10.x network
#   ansible.builtin.shell: ip route add 10.10.20.0/24 via 10.10.10.109
#   when: ansible_host | ipaddr('10.10.10.0/24')

# - name: Setting up IP route for 10.10.20.x network
#   ansible.builtin.shell: ip route add 10.10.10.0/24 via 10.10.20.205
#   when: ansible_host | ipaddr('10.10.20.0/24')

# - name: Set cron for automated routing for 10.10.10.x network
#   ansible.builtin.cron:
#     name: "route"
#     special_time: reboot
#     job: "ip route add 10.10.20.0/24 via 10.10.10.109"
#   when: ansible_host | ipaddr('10.10.10.0/24')

# - name: Set cron for automated routing for 10.10.20.x network
#   ansible.builtin.cron:
#     name: "route"
#     special_time: reboot
#     job: ip route add 10.10.10.0/24 via 10.10.20.205
#   when: ansible_host | ipaddr('10.10.20.0/24')

- name: Deploy HAProxy configuration
  ansible.builtin.template:
    src: templates/haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'

- name: Deploy keepalived master configuration
  ansible.builtin.template:
    src: templates/keepalived-master.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname == 'lb1'

- name: Deploy keepalived backup configuration
  ansible.builtin.template:
    src: templates/keepalived-backup.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname != 'lb1'

- name: Restart HAProxy
  ansible.builtin.systemd_service:
    name: haproxy
    state: restarted

- name: Restart keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    state: restarted
