# - name: Copy HAProxy configuration
#   ansible.builtin.template:
#     src: templates/haproxy.j2
#     dest: /etc/haproxy/haproxy.cfg
#     owner: root
#     group: root
#     mode: '0644'

- name: Copy HAProxy configuration
  ansible.builtin.copy:
    src: templates/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'


- name: Restart HAProxy
  ansible.builtin.systemd_service:
    name: haproxy
    state: restarted