---
- name: Update and upgrade system
  ansible.builtin.apt:
    update_cache: true
    upgrade: yes

- name: Install packages
  ansible.builtin.apt:
    pkg:
      - vim
      - qemu-guest-agent
      - iptables
      - nfs-common

# - name: Enable IPv4 forwarding
#   ansible.posix.sysctl:
#     name: net.ipv4.ip_forward
#     value: "1"
#     state: present
#     reload: true
#   tags: sysctl
#   when: inventory_hostname not in groups['loadbalancers']

# - name: Enable IPv6 forwarding
#   ansible.posix.sysctl:
#     name: net.ipv6.conf.all.forwarding
#     value: "1"
#     state: present
#     reload: true
#   tags: sysctl
#   when: inventory_hostname not in groups['loadbalancers']