- name: Prepare the environment / install dependencies
  hosts: dns
  become: yes
  roles:
    - role: install-deps

- name: Configure CoreDNS
  hosts: dns
  become: yes
  roles:
    - role: configure
