# - name: Prepare the environment / install dependencies
#   hosts: haproxy
#   become: yes
#   roles:
#     - role: install-deps

- name: Configure HAProxy
  hosts: haproxy
  become: yes
  roles:
    - role: configure
  
# - name: Configure Keepalived
#   hosts: haproxy
#   become: yes
#   roles:
#     - role: keepalived-setup

