- name: Get latest version of cloudflared
  ansible.builtin.get_url:
    url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
    dest: /tmp/cloudflared.deb
    mode: '0644'

- name: Install cloudflared
  ansible.builtin.command:
    cmd: dpkg -i /tmp/cloudflared.deb

- name: Restart cloudflared
  ansible.builtin.command:
    cmd: systemctl restart cloudflared

- name: Check cloudflared version
  ansible.builtin.command:
    cmd: cloudflared -version
  register: cloudflared_version
  changed_when: false

- name: Display cloudflared version
  ansible.builtin.debug:
    var: cloudflared_version.stdout