# - name: Run k3s executable on main server
#   shell: 'curl -sfL https://get.k3s.io | K3S_TOKEN={{ TOKEN }} sh -s - server --cluster-init --tls-san={{ vip }} --disable=servicelb --disable=traefik'
#   when: inventory_hostname == 'server1'

# - name: Run k3s executable on other servers
#   shell: "curl -sfL https://get.k3s.io | K3S_TOKEN={{ TOKEN }} sh -s - server --server https://{{ hostvars['server1']['ansible_host'] }}:6443 --tls-san={{ vip }} --disable=servicelb --disable=traefik"
#   when: inventory_hostname != 'server1' and inventory_hostname in groups['servers']

# - name: Install k3s on agents
#   shell: "curl -sfL https://get.k3s.io | K3S_TOKEN={{ TOKEN }} sh -s - agent --server https://{{ vip }}:6443"
#   when: inventory_hostname in groups['agents']

- name: Run k3s executable on main server
  ansible.builtin.debug:
    msg: 'curl -sfL https://get.k3s.io | K3S_TOKEN={{ TOKEN }} sh -s - server --cluster-init --tls-san={{ vip }} --disable=servicelb --disable=traefik --disable local-storage'
  when: inventory_hostname == 'server1'

- name: Run k3s executable on other servers
  ansible.builtin.debug:
    msg: "curl -sfL https://get.k3s.io | K3S_TOKEN={{ TOKEN }} sh -s - server --server https://{{ hostvars['server1']['ansible_host'] }}:6443 --tls-san={{ vip }} --disable=servicelb --disable=traefik --disable local-storage"
  when: inventory_hostname != 'server1' and inventory_hostname in groups['servers']

- name: Install k3s on agents
  ansible.builtin.debug:
    msg: "curl -sfL https://get.k3s.io | K3S_TOKEN={{ TOKEN }} sh -s - agent --server https://{{ vip }}:6443"
  when: inventory_hostname in groups['agents']
