- name: Create directory for RKE2 binary
  ansible.builtin.file:
    path: /etc/rancher/rke2/
    state: directory
    mode: '0755'

- name: Deploy RKE2 server configuration
  ansible.builtin.template:
    src: rke2-server-cluster.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname in groups['servers']

- name: Deploy RKE2 main server configuration
  ansible.builtin.template:
    src: rke2-server-init.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname == groups['servers'][0]

- name: Deploy RKE2 agent configuration
  ansible.builtin.template:
    src: rke2-agent.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname in groups['agents']
