- name: Update system
  ansible.builtin.apt:
    update_cache: true

- name: Install dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - bind9
    - bind9-doc
    - bind9-utils