---
- name: Update and upgrade system
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Install packages
  ansible.builtin.apt:
    pkg:
      - vim
      - qemu-guest-agent
      - iptables
      - nfs-common
      - cron

- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true
  tags: sysctl

- name: Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: true
  tags: sysctl

- name: Starting qemu-guest-agent service
  ansible.builtin.systemd:
    name: qemu-guest-agent
    enabled: true
    state: started


# ONLY FOR MULTISUBNET DEPLOYMENTS
# - name: Setting up IP route for 10.10.10.x network
#   ansible.builtin.shell: ip route add 10.10.20.0/24 via 10.10.10.109
#   when: ansible_host | ipaddr('10.10.10.0/24')

# - name: Setting up IP route for 10.10.20.x network
#   ansible.builtin.shell: ip route add 10.10.10.0/24 via 10.10.20.205
#   when: ansible_host | ipaddr('10.10.20.0/24')

# - name: Set cron for automated routing for 10.10.10.x network
#   ansible.builtin.cron:
#     name: "route"
#     special_time: reboot
#     job: "ip route add 10.10.20.0/24 via 10.10.10.109"
#   when: ansible_host | ipaddr('10.10.10.0/24')

# - name: Set cron for automated routing for 10.10.20.x network
#   ansible.builtin.cron:
#     name: "route"
#     special_time: reboot
#     job: ip route add 10.10.10.0/24 via 10.10.20.205
#   when: ansible_host | ipaddr('10.10.20.0/24')
